// API Configuration for GitHub Pages
// This file is automatically generated during deployment
// Update the API_BASE_URL below to point to your deployed FastAPI backend

const API_BASE_URL = (function() {
    // Auto-detect: if running locally, use localhost
    if (window.location.hostname === 'localhost' || 
        window.location.hostname === '127.0.0.1' ||
        window.location.hostname === '') {
        return 'http://127.0.0.1:8000';
    }
    
    // For GitHub Pages, use your deployed API URL
    // Update this with your actual API deployment URL
    return 'https://your-api-domain.com'; // TODO: Replace with your API URL
})();

// Make it globally available
window.API_BASE = API_BASE_URL;

console.log('API Base URL:', API_BASE_URL);

